package com.missioncontrol.mission.internal;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * The composite key of {@link RequiredSkillEntity}: a requirement and a skill.
 *
 * <p>A class rather than a record because JPA requires an embeddable id to have a no-argument
 * constructor and to be mutable enough for the provider to populate. {@code equals} and
 * {@code hashCode} are written out rather than generated by Lombok, since an id's identity
 * semantics are the one thing that should never quietly change with an annotation.
 */
@Embeddable
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
class RequiredSkillId implements Serializable {

    @Column(name = "crew_requirement_id", nullable = false)
    private UUID crewRequirementId;

    @Column(name = "skill_id", nullable = false)
    private UUID skillId;

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof RequiredSkillId that)) {
            return false;
        }
        return Objects.equals(crewRequirementId, that.crewRequirementId)
                && Objects.equals(skillId, that.skillId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(crewRequirementId, skillId);
    }
}
