package com.missioncontrol.crew.internal;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * The composite key of {@link CrewSkillEntity}: a crew member and a skill.
 *
 * <p>A class rather than a record because JPA requires an embeddable id to have a no-argument
 * constructor and to be mutable enough for the provider to populate. {@code equals} and
 * {@code hashCode} are written out rather than generated by Lombok, since an id's identity
 * semantics are the one thing that should never quietly change with an annotation.
 *
 * <p>The mirror image of {@code RequiredSkillId} on the mission side, and deliberately so: the two
 * tables express the same rule from opposite directions - what a person can do, and what a job
 * asks for.
 */
@Embeddable
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
class CrewSkillId implements Serializable {

    @Column(name = "crew_member_id", nullable = false)
    private UUID crewMemberId;

    @Column(name = "skill_id", nullable = false)
    private UUID skillId;

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof CrewSkillId that)) {
            return false;
        }
        return Objects.equals(crewMemberId, that.crewMemberId)
                && Objects.equals(skillId, that.skillId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(crewMemberId, skillId);
    }
}
